# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import prime_pb2 as prime__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in prime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrimeCheckerStub(object):
    """Service to check primality.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check = channel.unary_unary(
                '/prime.PrimeChecker/check',
                request_serializer=prime__pb2.PrimeCandidate.SerializeToString,
                response_deserializer=prime__pb2.Primality.FromString,
                _registered_method=True)


class PrimeCheckerServicer(object):
    """Service to check primality.
    """

    def check(self, request, context):
        """Determines the primality of an integer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrimeCheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check': grpc.unary_unary_rpc_method_handler(
                    servicer.check,
                    request_deserializer=prime__pb2.PrimeCandidate.FromString,
                    response_serializer=prime__pb2.Primality.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prime.PrimeChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prime.PrimeChecker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrimeChecker(object):
    """Service to check primality.
    """

    @staticmethod
    def check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prime.PrimeChecker/check',
            prime__pb2.PrimeCandidate.SerializeToString,
            prime__pb2.Primality.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
