exclude: '^$'

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: no-commit-to-branch
      args: [--branch, master, --branch, develop]
    - id: trailing-whitespace
    - id: check-added-large-files
      args: [maxkb=512]
    - id: check-ast
    - id: check-json
    - id: pretty-format-json
      args: [--autofix]
    - id: check-xml
    - id: check-yaml
    - id: check-merge-conflict
    - id: detect-private-key
    - id: name-tests-test
      args: ['--django']        # uncomment to change tests to 'test_*.py' rather '*_test.py'
    - id: requirements-txt-fixer
    - id: trailing-whitespace

  ## consider using seed-isort-config
  ## (pip install seed-isort-config)
  ##
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.21'
    hooks:
    - id: isort

  - repo: https://github.com/asottile/seed-isort-config
    rev: 'v2.1.1'
    hooks:
    - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    - id: mypy

  ## use either black *or* autopep8

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8

  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: ''  # Use the sha / tag you want to point at
  #   hooks:
  #   - id: autopep8

  # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  #   sha: v1.0.3
  #   hooks:
  #   - id: python-bandit-vulnerability-check

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

  - repo: https://github.com/milin/giticket
    rev: 6f166c66f2423e8e27898b39385d1166f9b643a3
    hooks:
    - id: giticket  # Prepend the commit message with the JIRA ticket
      args: ['--regex=(?:feature|bugfix|support|hotfix)/(OND[0-9]{3}-[0-9]{1,5})[_-][\w-]+',
             '--format=[{ticket}] {commit_msg}',
             '--mode=regex_match']
